name: "Push to cachix"
on:
  pull_request:
  push:
jobs:
  push-to-cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v25
    - uses: cachix/cachix-action@v14
      with:
        name: moxpaper
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix build --no-link --print-out-paths --impure > /tmp/paths
    - run: cat /tmp/paths | cachix push moxpaper
